### PR TITLE
fixes #89

### LINKED ISSUE #89: Unable to run the scripts on Windows 10 to build docker image
The spawn functionality only seems to be work on linux machines (Tested on Mac).

Using cross-spawn would allow this to be easily used on a Windows 10 install and hopefully allow more people to contribute to this great project idea.

### PR DESCRIPTION
**Pull request by bigmadkev**
Updates to allow Windows 10 devs to run locally.
* added .gitattributes to ensure that CSV file checksout with LF eof else tests fail
* updated devDependencies in ./package.json to have cross-spawn
* update build/dockerImage.js to use cross-spawn
* update client & server package files to remove single quoutes from
* matchers so that they work on Windows 10

### CODE REVIEW

**Comment by xeronimus** [comment]
Hey there, thanks a lot for your contributions! I'm currently on vacation and will check your PRs next week.

**Comment by bigmadkev** [comment]
No worries,

Sorry for the noise, was trying to get my head around. When I used to code
professionally it was still subversion :-)

Happy to help I've wanted to learn react so this seems a nice way to go.

Cheers
.enjoy your break !

**Comment by xeronimus** [comment]
not quite sure if I agree with removing single quotes around globs .   see https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784

what do you think ?  (I never code/develop on windows, so I wouldn't know..)

**Comment by bigmadkev** [comment]
I'll have another play, I ran the code on my windows and Mac installs both seemed to work. Will double check with the insight of that article, although 4 years old so things in npm may have moved on :-)

**Pull request merged**
